# Book settings

title: Deep Learning Notebooks and Solutions Manual 
author: Brian J. Lee
logo: logo.png

execute:
  execute_notebooks: force

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/brianjsl/DL_solutions  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  home_page_in_navbar : true
  use_repository_button: true
  use_issues_button: true
  comments:
    hypothesis: true
  extra_footer : |
    <div>
    <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/"><img src="https://licensebuttons.net/l/by-nc-sa/3.0/88x31.png"></a>
        All content on this site (unless otherwise specified) is licensed under the <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0 license</a>
    </div>

sphinx:
  extra_extensions:
    - sphinx_tabs.tabs
    - sphinxext.opengraph
  html_context: 
    default_mode: light
  html_theme: classic
  html_show_copyright: true
  config:
    ogp_site_url: "https://github.com/brianjsl/DL_solutions"
    ogp_description_length: 200
    mathjax_config:
      TeX:
        Macros:
          "\nn": "\\mathbb{N}"
          "\rr": "\\mathbb{R}"

launch_buttons:
  notebook_interface: classic 
  binderhub_url: https://mybinder.org
  colab_url: https://colab.research.google.com